### ISSUE TITLE
error when use babel-preset-env

### ISSUE THREAD

**Issue by soakit** [QingWei-Li/babel-plugin-component#22]
babel
```json
{
	"presets": [
		["env", {
			"useBuiltIns": "usage",
			"modules": false,
			"targets": {
				"browsers": ["last 5 versions", "ie >= 9"]
			}
		}]
	],
	"comments": false,
	"env": {
		"test": {
			"presets": ["env", "stage-2"],
			"plugins": ["istanbul"]
		}
	},
	"plugins": [
		"lodash",
		["transform-object-rest-spread", { "useBuiltIns": true }],
		["component", [
			{
			  "libraryName": "element-ui",
			  "styleLibraryName": "theme-default"
			}
		  ]]
	]
}
```

 error  in ./src/utils/logic-error.js

Module build failed: TypeError: E:\git\byd\web\src\utils\logic-error.js: Cannot read property 'file' of undefined
    at buildExpressionHandler (E:\git\byd\web\node_modules\babel-plugin-component\lib\core.js:125:26)
    at PluginPass.IfStatement (E:\git\byd\web\node_modules\babel-plugin-component\lib\core.js:266:11)
    at newFn (E:\git\byd\web\node_modules\babel-traverse\lib\visitors.js:236:21)
    at NodePath._call (E:\git\byd\web\node_modules\babel-traverse\lib\path\context.js:68:19)
    at NodePath.call (E:\git\byd\web\node_modules\babel-traverse\lib\path\context.js:42:17)
    at NodePath.visit (E:\git\byd\web\node_modules\babel-traverse\lib\path\context.js:99:12)
    at TraversalContext.visitQueue (E:\git\byd\web\node_modules\babel-traverse\lib\context.js:137:18)
    at TraversalContext.visitMultiple (E:\git\byd\web\node_modules\babel-traverse\lib\context.js:91:17)
    at TraversalContext.visit (E:\git\byd\web\node_modules\babel-traverse\lib\context.js:176:19)
    at Function.traverse.node (E:\git\byd\web\node_modules\babel-traverse\lib\index.js:108:17)
    at NodePath.visit (E:\git\byd\web\node_modules\babel-traverse\lib\path\context.js:110:19)
    at TraversalContext.visitQueue (E:\git\byd\web\node_modules\babel-traverse\lib\context.js:137:18)
    at TraversalContext.visitSingle (E:\git\byd\web\node_modules\babel-traverse\lib\context.js:96:19)
    at TraversalContext.visit (E:\git\byd\web\node_modules\babel-traverse\lib\context.js:178:19)
    at Function.traverse.node (E:\git\byd\web\node_modules\babel-traverse\lib\index.js:108:17)
    at NodePath.visit (E:\git\byd\web\node_modules\babel-traverse\lib\path\context.js:110:19)

 @ ./src/utils/api-client.js 3:0-39
 @ ./src/store/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by yoyo837** [comment]
The same.

Cannot read property 'file' of undefined

```javascript
['component', [{ libraryName: 'element-ui', styleLibraryName: 'theme-default' }]]
```
