### ISSUE TITLE
按需引入官方问题配置出错

### ISSUE THREAD

**Issue by AdamEva916** [QingWei-Li/babel-plugin-component#68]
第一个问题
Error: Cannot find module 'babel-preset-es2015'
        Require stack:
        - F:\vue\dev\dev\node_modules\@babel\core\lib\config\files\plugins.js
        - F:\vue\dev\dev\node_modules\@babel\core\lib\config\files\index.js  
        - F:\vue\dev\dev\node_modules\@babel\core\lib\index.js
        - F:\vue\dev\dev\node_modules\@vue\cli-plugin-babel\index.js
        - F:\vue\dev\dev\node_modules\@vue\cli-service\lib\Service.js

第二个问题
Error: .plugins[0][1] must be an object, false, or undefined
Error: .plugins[0][1] must be an object, false, or undefined
    at validate (F:\vue\dev\dev\node_modules\@babel\core\lib\config\validation\options.js:86:25)
    at F:\vue\dev\dev\node_modules\@babel\core\lib\config\config-chain.js:165:34
    at cachedFunction (F:\vue\dev\dev\node_modules\@babel\core\lib\config\caching.js:48:27)
    at cachedFunction.next (<anonymous>)
    at evaluateSync (F:\vue\dev\dev\node_modules\gensync\index.js:251:28)
    at sync (F:\vue\dev\dev\node_modules\gensync\index.js:89:14)
    at buildRootChain (F:\vue\dev\dev\node_modules\@babel\core\lib\config\config-chain.js:77:27)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (F:\vue\dev\dev\node_modules\@babel\core\lib\config\partial.js:79:62)
    at loadPrivatePartialConfig.next (<anonymous>)

旧配置项
{
  "presets": [["es2015", { "modules": false }]],
  "plugins": [
    [
      "component",
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      }
    ]
  ]
}

大佬们能不能改改官方文档，按需文档一步步走真的出错，不好找原因

**Comment by purer01** [comment]
我也遇到了相同的问题，可以将配置项里的`"presets": [["es2015", { "modules": false }]],`修改为：`"presets": [["@babel/preset-env", { "modules": false }]],`应该就可以解决。
原因：看报错内容应该与你的babel版本有关系（终端执行`babel --version`即可查看`babel`的版本号），对于babel 6来说，使用的就是`babel-preset-es2015`，但如果对于babel 7来说，应该使用的是`@babel/preset-es2015`。
从报错看出你使用的应该是7这个版本，对于7来说，`babel-preset-es2015`已经废弃了。
